"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    Object.defineProperty(o, k2, { enumerable: true, get: function() { return m[k]; } });
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (Object.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.Error = exports.Modal = exports.InputCcv = exports.InputDate = exports.InputName = exports.InputNumber = exports.SendButtonDisable = exports.SendButton = exports.FormGroupFlex = exports.FormGroup = exports.Form = exports.Signature = exports.Data = exports.MagBar = exports.Back = exports.Group = exports.FlexBox = exports.Legal = exports.Label = exports.Front = exports.Card = exports.Wrapper = exports.ButtonContainer = void 0;
var styled_components_1 = __importStar(require("styled-components"));
var calendar = require('../img/icons/calendar.svg'), crediCard = require('../img/icons/credit-card.svg'), user = require('../img/icons/user.svg'), lock = require('../img/icons/lock.svg');
exports.ButtonContainer = styled_components_1.default.button(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n\tdisplay: flex;\n\tjustify-content: center;\n\talign-items: center;\n\twidth: 44px;\n\theight: 44px;\n\tbackground: #2364d2;\n\tposition: relative;\n\ttop: -25px;\n\tborder: none;\n\tborder-radius: 50%;\n\tz-index: 20;\n\tbox-shadow: -5px 4px 8px rgba(24, 56, 182, 0.4);\n\tcursor: pointer;\n\ttransition: all 0.4s ease;\n\ttransform: ", ";\n\t:focus {\n\t\toutline: none;\n\t\tborder: 0;\n\t}\n\t:hover {\n\t\tbackground: #1850b1;\n\t}\n"], ["\n\tdisplay: flex;\n\tjustify-content: center;\n\talign-items: center;\n\twidth: 44px;\n\theight: 44px;\n\tbackground: #2364d2;\n\tposition: relative;\n\ttop: -25px;\n\tborder: none;\n\tborder-radius: 50%;\n\tz-index: 20;\n\tbox-shadow: -5px 4px 8px rgba(24, 56, 182, 0.4);\n\tcursor: pointer;\n\ttransition: all 0.4s ease;\n\ttransform: ", ";\n\t:focus {\n\t\toutline: none;\n\t\tborder: 0;\n\t}\n\t:hover {\n\t\tbackground: #1850b1;\n\t}\n"])), function (props) { return props.activeButton && 'rotate(45deg)'; });
exports.Wrapper = styled_components_1.default.div(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n\tposition: relative;\n\twidth: 80%;\n\tmax-width: 1000px;\n\tpadding: 40px 20px;\n\tmargin: auto;\n\tdisplay: flex;\n\tflex-direction: column;\n\tbackground: #ccc;\n\talign-items: center;\n\t.modal {\n\t}\n"], ["\n\tposition: relative;\n\twidth: 80%;\n\tmax-width: 1000px;\n\tpadding: 40px 20px;\n\tmargin: auto;\n\tdisplay: flex;\n\tflex-direction: column;\n\tbackground: #ccc;\n\talign-items: center;\n\t.modal {\n\t}\n"])));
exports.Card = styled_components_1.default.article(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n\twidth: 100%;\n\tmax-width: 344px;\n\tposition: relative;\n\tcolor: #fff;\n\ttransition: 0.6s ease all;\n\ttransform: rotateY(0deg);\n\ttransform-style: preserve-3d;\n\tcursor: pointer;\n\tz-index: 10;\n\ttransform: ", ";\n\t& > div {\n\t\tbackground-color: #0b6ab1;\n\t\tpadding: 18px;\n\t\tborder-radius: 14px;\n\t\tmin-height: 206px;\n\t\tdisplay: flex;\n\t\tflex-direction: column;\n\t\tjustify-content: space-between;\n\t\tbox-shadow: 0 10px 10px 0 rgba(90, 116, 148, 0.3);\n\t}\n"], ["\n\twidth: 100%;\n\tmax-width: 344px;\n\tposition: relative;\n\tcolor: #fff;\n\ttransition: 0.6s ease all;\n\ttransform: rotateY(0deg);\n\ttransform-style: preserve-3d;\n\tcursor: pointer;\n\tz-index: 10;\n\ttransform: ", ";\n\t& > div {\n\t\tbackground-color: #0b6ab1;\n\t\tpadding: 18px;\n\t\tborder-radius: 14px;\n\t\tmin-height: 206px;\n\t\tdisplay: flex;\n\t\tflex-direction: column;\n\t\tjustify-content: space-between;\n\t\tbox-shadow: 0 10px 10px 0 rgba(90, 116, 148, 0.3);\n\t}\n"])), function (props) { return props.activeCard && 'rotateY(180deg)'; });
exports.Front = styled_components_1.default.div(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n\twidth: 100%;\n\tbackface-visibility: hidden;\n\tbackground-image: linear-gradient(45deg, #0b6ab1 0%, #26d886 100%);\n\t& .logo {\n\t\ttext-align: right;\n\t\tmin-height: 30px;\n\t\timg {\n\t\t\twidth: 100%;\n\t\t\tmax-width: 58px;\n\t\t\theight: 90%;\n\t\t\tmin-height: 36px;\n\t\t\tobject-fit: cover;\n\t\t}\n\t}\n\t& > img {\n\t\tposition: relative;\n\t\ttop: -6px;\n\t\twidth: 100%;\n\t\tmax-width: 40px;\n\t\tmargin-bottom: 6px;\n\t}\n"], ["\n\twidth: 100%;\n\tbackface-visibility: hidden;\n\tbackground-image: linear-gradient(45deg, #0b6ab1 0%, #26d886 100%);\n\t& .logo {\n\t\ttext-align: right;\n\t\tmin-height: 30px;\n\t\timg {\n\t\t\twidth: 100%;\n\t\t\tmax-width: 58px;\n\t\t\theight: 90%;\n\t\t\tmin-height: 36px;\n\t\t\tobject-fit: cover;\n\t\t}\n\t}\n\t& > img {\n\t\tposition: relative;\n\t\ttop: -6px;\n\t\twidth: 100%;\n\t\tmax-width: 40px;\n\t\tmargin-bottom: 6px;\n\t}\n"])));
exports.Label = styled_components_1.default.p(templateObject_5 || (templateObject_5 = __makeTemplateObject(["\n\tfont-size: 0.9rem;\n\tcolor: #fff;\n"], ["\n\tfont-size: 0.9rem;\n\tcolor: #fff;\n"])));
exports.Legal = styled_components_1.default.p(templateObject_6 || (templateObject_6 = __makeTemplateObject(["\n\tfont-size: 0.8rem;\n\tline-height: 1rem;\n\tcolor: ", ";\n"], ["\n\tfont-size: 0.8rem;\n\tline-height: 1rem;\n\tcolor: ", ";\n"])), function (props) { return (props.color ? '#2364d2;' : '#f2f2f2'); });
exports.FlexBox = styled_components_1.default.div(templateObject_7 || (templateObject_7 = __makeTemplateObject(["\n\tdisplay: flex;\n\tjustify-content: space-between;\n"], ["\n\tdisplay: flex;\n\tjustify-content: space-between;\n"])));
exports.Group = styled_components_1.default.div(templateObject_8 || (templateObject_8 = __makeTemplateObject(["\n\t&.name {\n\t\tmax-width: 240px;\n\t\twidth: 100%;\n\t}\n\t& p {\n\t\toverflow: hidden;\n\t\tmax-width: 100%;\n\t\tfont-size: 0.9rem;\n\t\tline-height: 20px;\n\t\theight: 20px;\n\t}\n\t&.number {\n\t\tmargin-bottom: 6px;\n\t}\n\t&.signature {\n\t\twidth: 70%;\n\t}\n\t&.ccv {\n\t\twidth: 20%;\n\t\t> .ccv {\n\t\t\tbackground: #fff;\n\t\t\theight: 30px;\n\t\t\tline-height: 10px;\n\t\t\tcolor: #000;\n\t\t\tpadding: 10px;\n\t\t\ttext-align: center;\n\t\t}\n\t}\n"], ["\n\t&.name {\n\t\tmax-width: 240px;\n\t\twidth: 100%;\n\t}\n\t& p {\n\t\toverflow: hidden;\n\t\tmax-width: 100%;\n\t\tfont-size: 0.9rem;\n\t\tline-height: 20px;\n\t\theight: 20px;\n\t}\n\t&.number {\n\t\tmargin-bottom: 6px;\n\t}\n\t&.signature {\n\t\twidth: 70%;\n\t}\n\t&.ccv {\n\t\twidth: 20%;\n\t\t> .ccv {\n\t\t\tbackground: #fff;\n\t\t\theight: 30px;\n\t\t\tline-height: 10px;\n\t\t\tcolor: #000;\n\t\t\tpadding: 10px;\n\t\t\ttext-align: center;\n\t\t}\n\t}\n"])));
exports.Back = styled_components_1.default.div(templateObject_9 || (templateObject_9 = __makeTemplateObject(["\n\tbackface-visibility: hidden;\n\tbackground-image: linear-gradient(-45deg, #0b6ab1 0%, #26d886 100%);\n\tposition: absolute;\n\ttop: 0;\n\ttransform: rotateY(180deg);\n\tbackface-visibility: hidden;\n"], ["\n\tbackface-visibility: hidden;\n\tbackground-image: linear-gradient(-45deg, #0b6ab1 0%, #26d886 100%);\n\tposition: absolute;\n\ttop: 0;\n\ttransform: rotateY(180deg);\n\tbackface-visibility: hidden;\n"])));
exports.MagBar = styled_components_1.default.div(templateObject_10 || (templateObject_10 = __makeTemplateObject(["\n\theight: 36px;\n\twidth: 100%;\n\tbackground: #000;\n\tposition: absolute;\n\ttop: 20px;\n\tleft: 0;\n"], ["\n\theight: 36px;\n\twidth: 100%;\n\tbackground: #000;\n\tposition: absolute;\n\ttop: 20px;\n\tleft: 0;\n"])));
exports.Data = styled_components_1.default.div(templateObject_11 || (templateObject_11 = __makeTemplateObject(["\n\tmargin-top: 44px;\n\tdisplay: flex;\n\tjustify-content: space-between;\n\t& p {\n\t\tmargin-bottom: 5px;\n\t}\n"], ["\n\tmargin-top: 44px;\n\tdisplay: flex;\n\tjustify-content: space-between;\n\t& p {\n\t\tmargin-bottom: 5px;\n\t}\n"])));
exports.Signature = styled_components_1.default.div(templateObject_12 || (templateObject_12 = __makeTemplateObject(["\n\twidth: 100%;\n\theight: 30px;\n\tbackground: repeating-linear-gradient(\n\t\tskyblue 0,\n\t\tskyblue 5px,\n\t\torange 5px,\n\t\torange 10px\n\t);\n\t& > p {\n\t\toverflow: hidden;\n\t\tmax-width: 100%;\n\t\theight: 100%;\n\t\tline-height: 30px;\n\t\tfont-family: Georgia, 'Times New Roman', Times, serif;\n\t\tcolor: #000;\n\t\tfont-size: 1.4rem;\n\t\tpadding: 0 10px;\n\t\ttext-transform: capitalize;\n\t\tword-break: break-all;\n\t}\n"], ["\n\twidth: 100%;\n\theight: 30px;\n\tbackground: repeating-linear-gradient(\n\t\tskyblue 0,\n\t\tskyblue 5px,\n\t\torange 5px,\n\t\torange 10px\n\t);\n\t& > p {\n\t\toverflow: hidden;\n\t\tmax-width: 100%;\n\t\theight: 100%;\n\t\tline-height: 30px;\n\t\tfont-family: Georgia, 'Times New Roman', Times, serif;\n\t\tcolor: #000;\n\t\tfont-size: 1.4rem;\n\t\tpadding: 0 10px;\n\t\ttext-transform: capitalize;\n\t\tword-break: break-all;\n\t}\n"])));
exports.Form = styled_components_1.default.form(templateObject_13 || (templateObject_13 = __makeTemplateObject(["\n\tbackground: #fff;\n\twidth: 100%;\n\tmax-width: 406px;\n\tpadding: 108px 30px 30px;\n\tborder-radius: 16px;\n\tposition: relative;\n\ttop: -120px;\n\tz-index: 1;\n\ttransition: all 0.4s ease-out;\n\tclip-path: polygon(0 0, 100% 0, 100% 0, 0 0);\n\tclip-path: ", ";\n"], ["\n\tbackground: #fff;\n\twidth: 100%;\n\tmax-width: 406px;\n\tpadding: 108px 30px 30px;\n\tborder-radius: 16px;\n\tposition: relative;\n\ttop: -120px;\n\tz-index: 1;\n\ttransition: all 0.4s ease-out;\n\tclip-path: polygon(0 0, 100% 0, 100% 0, 0 0);\n\tclip-path: ",
    ";\n"])), function (props) {
    return props.activeForm && 'polygon(0 0, 100% 0, 100% 100%, 0 100%)';
});
exports.FormGroup = styled_components_1.default.div(templateObject_16 || (templateObject_16 = __makeTemplateObject(["\n\t& label {\n\t\tdisplay: block;\n\t\tcolor: #7d8994;\n\t\tfont-size: 0.9rem;\n\t}\n\t& input {\n\t\tborder: 1px solid #ced6e0;\n\t\tfont-size: 0.9rem;\n\t\theight: 32px;\n\t\twidth: 100%;\n\t\tpadding: 6px 12px 6px 34px;\n\t\tmargin-bottom: 12px;\n\t\ttransition: 0.4s ease all;\n\t\tborder-radius: 4px;\n\t\t", ";\n\t\t", ";\n\t\t:focus {\n\t\t\toutline: rgba(4, 4, 4, 0.5);\n\t\t\tborder: 1.3px solid #93bded;\n\t\t\tbox-shadow: 0px 0px 4px #93bded;\n\t\t}\n\t}\n"], ["\n\t& label {\n\t\tdisplay: block;\n\t\tcolor: #7d8994;\n\t\tfont-size: 0.9rem;\n\t}\n\t& input {\n\t\tborder: 1px solid #ced6e0;\n\t\tfont-size: 0.9rem;\n\t\theight: 32px;\n\t\twidth: 100%;\n\t\tpadding: 6px 12px 6px 34px;\n\t\tmargin-bottom: 12px;\n\t\ttransition: 0.4s ease all;\n\t\tborder-radius: 4px;\n\t\t",
    ";\n\t\t",
    ";\n\t\t:focus {\n\t\t\toutline: rgba(4, 4, 4, 0.5);\n\t\t\tborder: 1.3px solid #93bded;\n\t\t\tbox-shadow: 0px 0px 4px #93bded;\n\t\t}\n\t}\n"])), function (props) {
    return props.valid && styled_components_1.css(templateObject_14 || (templateObject_14 = __makeTemplateObject(["\n\t\t\t\tborder: 1px solid #27ae60 !important;\n\t\t\t\tbox-shadow: 0px 0px 2px #27ae60;\n\t\t\t"], ["\n\t\t\t\tborder: 1px solid #27ae60 !important;\n\t\t\t\tbox-shadow: 0px 0px 2px #27ae60;\n\t\t\t"])));
}, function (props) {
    return props.valid === false && styled_components_1.css(templateObject_15 || (templateObject_15 = __makeTemplateObject(["\n\t\t\t\tborder: 1px solid #e74c3c !important;\n\t\t\t\tbox-shadow: 0px 0px 2px #e74c3c;\n\t\t\t"], ["\n\t\t\t\tborder: 1px solid #e74c3c !important;\n\t\t\t\tbox-shadow: 0px 0px 2px #e74c3c;\n\t\t\t"])));
});
exports.FormGroupFlex = styled_components_1.default.div(templateObject_17 || (templateObject_17 = __makeTemplateObject(["\n\tdisplay: flex;\n\tjustify-content: space-between;\n\tdiv:first-child {\n\t\tmargin-right: 8px;\n\t\twidth: 50%;\n\t}\n\tdiv:nth-child(2) {\n\t\twidth: 50%;\n\t\tmargin-left: 8px;\n\t}\n"], ["\n\tdisplay: flex;\n\tjustify-content: space-between;\n\tdiv:first-child {\n\t\tmargin-right: 8px;\n\t\twidth: 50%;\n\t}\n\tdiv:nth-child(2) {\n\t\twidth: 50%;\n\t\tmargin-left: 8px;\n\t}\n"])));
exports.SendButton = styled_components_1.default.button(templateObject_18 || (templateObject_18 = __makeTemplateObject(["\n\tborder: none;\n\tborder-radius: 6px;\n\twidth: 100%;\n\tmargin-top: 12px;\n\theight: 32px;\n\tfont-size: 0.9rem;\n\tcolor: #fff;\n\tcursor: pointer;\n\tbackground: #2364d2;\n\t:hover {\n\t\tbackground: #1850b1;\n\t\tbox-shadow: 0px 0px 4px #93bded;\n\t}\n\t:focus {\n\t\toutline: rgba(4, 4, 4, 0.5);\n\t\tbox-shadow: 0px 0px 6px #93bded;\n\t}\n"], ["\n\tborder: none;\n\tborder-radius: 6px;\n\twidth: 100%;\n\tmargin-top: 12px;\n\theight: 32px;\n\tfont-size: 0.9rem;\n\tcolor: #fff;\n\tcursor: pointer;\n\tbackground: #2364d2;\n\t:hover {\n\t\tbackground: #1850b1;\n\t\tbox-shadow: 0px 0px 4px #93bded;\n\t}\n\t:focus {\n\t\toutline: rgba(4, 4, 4, 0.5);\n\t\tbox-shadow: 0px 0px 6px #93bded;\n\t}\n"])));
exports.SendButtonDisable = styled_components_1.default.button(templateObject_19 || (templateObject_19 = __makeTemplateObject(["\n\tborder: none;\n\tborder-radius: 6px;\n\twidth: 100%;\n\tmargin-top: 12px;\n\theight: 32px;\n\tfont-size: 0.9rem;\n\tcolor: #fff;\n\tcursor: not-allowed;\n\tbackground: #9fb1aa;\n"], ["\n\tborder: none;\n\tborder-radius: 6px;\n\twidth: 100%;\n\tmargin-top: 12px;\n\theight: 32px;\n\tfont-size: 0.9rem;\n\tcolor: #fff;\n\tcursor: not-allowed;\n\tbackground: #9fb1aa;\n"])));
exports.InputNumber = styled_components_1.default.input(templateObject_20 || (templateObject_20 = __makeTemplateObject(["\n\tbackground: url(", ");\n\tbackground-repeat: no-repeat;\n\tbackground-size: 20px;\n\tbackground-position: 8px center;\n"], ["\n\tbackground: url(", ");\n\tbackground-repeat: no-repeat;\n\tbackground-size: 20px;\n\tbackground-position: 8px center;\n"])), crediCard);
exports.InputName = styled_components_1.default.input(templateObject_21 || (templateObject_21 = __makeTemplateObject(["\n\tbackground: url(", ");\n\tbackground-repeat: no-repeat;\n\tbackground-size: 18px;\n\tbackground-position: 8px center;\n"], ["\n\tbackground: url(", ");\n\tbackground-repeat: no-repeat;\n\tbackground-size: 18px;\n\tbackground-position: 8px center;\n"])), user);
exports.InputDate = styled_components_1.default.input(templateObject_22 || (templateObject_22 = __makeTemplateObject(["\n\tbackground: url(", ");\n\tbackground-repeat: no-repeat;\n\tbackground-size: 18px;\n\tbackground-position: 8px center;\n"], ["\n\tbackground: url(", ");\n\tbackground-repeat: no-repeat;\n\tbackground-size: 18px;\n\tbackground-position: 8px center;\n"])), calendar);
exports.InputCcv = styled_components_1.default.input(templateObject_23 || (templateObject_23 = __makeTemplateObject(["\n\tbackground: url(", ");\n\tbackground-repeat: no-repeat;\n\tbackground-size: 18px;\n\tbackground-position: 8px center;\n"], ["\n\tbackground: url(", ");\n\tbackground-repeat: no-repeat;\n\tbackground-size: 18px;\n\tbackground-position: 8px center;\n"])), lock);
exports.Modal = styled_components_1.default.div(templateObject_24 || (templateObject_24 = __makeTemplateObject(["\n\tposition: absolute;\n\twidth: 90%;\n\tmax-width: 346px;\n\theight: 320px;\n\tbackground: #fff;\n\tborder-radius: 12px;\n\ttop: 20%;\n\tbox-shadow: 0px 0px 26px #9e9e9e;\n\tdisplay: flex;\n\tjustify-content: center;\n\talign-items: center;\n\tpadding: 40px;\n\tz-index: 200;\n"], ["\n\tposition: absolute;\n\twidth: 90%;\n\tmax-width: 346px;\n\theight: 320px;\n\tbackground: #fff;\n\tborder-radius: 12px;\n\ttop: 20%;\n\tbox-shadow: 0px 0px 26px #9e9e9e;\n\tdisplay: flex;\n\tjustify-content: center;\n\talign-items: center;\n\tpadding: 40px;\n\tz-index: 200;\n"])));
exports.Error = styled_components_1.default.small(templateObject_25 || (templateObject_25 = __makeTemplateObject(["\n\tdisplay: block;\n\tfont-size: 0.9rem;\n\tline-height: 1.4rem;\n\tcolor: #e74c3c;\n\tposition: relative;\n\ttop: -0.3rem;\n"], ["\n\tdisplay: block;\n\tfont-size: 0.9rem;\n\tline-height: 1.4rem;\n\tcolor: #e74c3c;\n\tposition: relative;\n\ttop: -0.3rem;\n"])));
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5, templateObject_6, templateObject_7, templateObject_8, templateObject_9, templateObject_10, templateObject_11, templateObject_12, templateObject_13, templateObject_14, templateObject_15, templateObject_16, templateObject_17, templateObject_18, templateObject_19, templateObject_20, templateObject_21, templateObject_22, templateObject_23, templateObject_24, templateObject_25;
